name: alfie_flutter
description: "A Flutter eCommerce Boilerplate Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  expandable_page_view: ^1.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  gql: ^1.0.1
  graphql: ^5.2.3
  graphql_flutter: ^5.2.1
  hooks_riverpod: ^3.2.1
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  graphql_codegen: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/

  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
          weight: 400
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
